language: php

php:
- 5.5
- 5.6
- 7.0

matrix:
  allow_failures:
    - php: 7.0

sudo: false

before_script:
- npm install -g drakov
- drakov -f ./apiary.apib -p 3000&
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-source

script:
- vendor/bin/behat --suite=develop

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/234214bec6e2c6e1c703
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
