language: php

matrix:
  include:
    - php: 5.5
      env: APIBLUPRINT=./apiary.apib BEHAT_SUITE=develop
      branches:
        except:
          - master
    - php: 5.6
      env: APIBLUPRINT=./apiary.apib BEHAT_SUITE=develop
      branches:
        except:
          - master
    - php: 5.6
      env: APIBLUPRINT=./errors.apib BEHAT_SUITE=errors
      branches:
        except:
          - master
    - php: 5.6
      env: APIBLUPRINT=./apiary.apib BEHAT_SUITE=production
      branches:
        only:
          - master
    - php: 5.6
      env: APIBLUPRINT=./errors.apib BEHAT_SUITE=prod_errors
      branches:
        only:
          - master
    - php: 7.0
      env: APIBLUPRINT=./apiary.apib BEHAT_SUITE=develop
      branches:
        except:
          - master
  allow_failures:
    - php: 7.0

sudo: false

before_script:
- npm install -g drakov
- drakov -f $APIBLUPRINT -p 3000&
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-source

script:
- vendor/bin/behat --suite=$BEHAT_SUITE

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/234214bec6e2c6e1c703
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
