language: php

php:
- 5.4
- 5.5
- 5.6
- 7

before_script:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-source
- npm install -g drakov
- drakov -f ./apiary.apib -p 3000&
- sleep 3 # Drakov needs some time to start

script:
- tests/behat/bin/behat -c tests/behat/behat-dev.yml

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/234214bec6e2c6e1c703
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
