language: php

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
  allow_failures:
    - php: 7.0

sudo: false

before_script:
- GIT_BRANCH=$(git branch --contains HEAD)
- echo $GIT_BRANCH
- if [[ "$GIT_BRANCH" == '* master' ]]; then echo 'Drakov is not necessary'; else npm install -g drakov; drakov -f ./apiary.apib -p 3000& drakov -f ./errors.apib -p 3001& fi
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-source

script:
- if [[ "$GIT_BRANCH" == '* master' ]]; then echo 'Testing develop'; vendor/bin/behat --suite=develop; vendor/bin/behat --suite=errors; else echo 'Testing production'; vendor/bin/behat --suite=production; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/234214bec6e2c6e1c703
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
