language: php

php:
  - 7.0
env:
  - TEST_SUITE=develop TEST_FILE=./apiary.apib
  - TEST_SUITE=errors TEST_FILE=./errors.apib

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
- npm install
- ./node_modules/.bin/drakov -f $TEST_FILE -p 3000&
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-dist

script:
- echo "Testing $TEST_SUITE"; vendor/bin/behat --suite=$TEST_SUITE;

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/234214bec6e2c6e1c703
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
